# 20260917 - need explicit backend
backend = "glx";

# 20220221 - https://github.com/fennerm/flashfocus
detect-client-opacity = true;

# 20241106
#"0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
# Type specifier is deprecated. Type "a" specified on target "_NET_WM_STATE" will be ignored, you can remove it.
# Format specifier is deprecated. Format "32" specified on target "_NET_WM_STATE" will be ignored, you can remove it.
# 20260917: also see --transparent-clipping
#
# syntax: PERCENT:PATTERN, like 50:name *= "Firefox"
#opacity-rule = [
#  "0:_NET_WM_STATE@ *= '_NET_WM_STATE_HIDDEN'",
#  "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
#  "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
#];

# i3wm xterm xprop info when
# focused:        _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_FOCUSED
# visible:        _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ
# behind another: _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_HIDDEN
rules: ({
  match = "(class_g = 'URxvt' || class_g = 'Alacritty' || class_g = 'XTerm')"
          " && !focused";
  opacity = 0.95;
 },{
  match = "name = 'cpt_frame_xcb_window'"; # 20241106 - zoom green box share shadowing everything
  shadow = false;
 },{
  match = "class_g = 'firefox' && argb"; # 20260917 - suggestd by archlinux wiki
  shadow = false;
 },
{
  match = "_NET_WM_STATE@[*] = '_NET_WM_STATE_HIDDEN'";
  opacity = 0;
 }, 
)
