[greenclip]
 max_history_length = 50
 history_file = "~/.cache/greenclip.history"
 image_cache_directory = "/tmp/greenclip/"
 use_primary_selection_as_input = true
 trim_space_from_selection = true
 enable_image_support = true
 max_selection_size_bytes = 0
 blacklisted_applications = []
 static_history = []
